urls.py
__author__ = 'ismailsunni'

from django.conf.urls import patterns, url

from geosafe.views import metasearch
from geosafe.views.analysis import (
    AnalysisListView,
    AnalysisCreateView,
    AnalysisDetailView,
    impact_function_filter,
    layer_tiles,
    layer_metadata,
    layer_archive,
    layer_list, rerun_analysis,
    analysis_json, toggle_analysis_saved, download_report, layer_panel,
    analysis_summary, cancel_analysis, validate_analysis_extent)

urlpatterns = patterns(
    '',
    url(
        r'^analysis/create(?:/(?P<pk>\d*))?$',
        AnalysisCreateView.as_view(),
        name='analysis-create'
    ),
    url(
        r'^analysis/(?:/user/(?P<user>\d*))?$',
        AnalysisListView.as_view(),
        name='analysis-list'
    ),
    url(
        r'^analysis/impact-function-filter$',
        impact_function_filter,
        name='impact-function-filter'
    ),
    url(
        r'^analysis/(?P<pk>\d+)$',
        AnalysisDetailView.as_view(),
        name='analysis-detail'
    ),
    url(
        r'^analysis/layer-tiles$',
        layer_tiles,
        name='layer-tiles'
    ),
    url(
        r'^analysis/layer-metadata/(?P<layer_id>\d+)',
        layer_metadata,
        name='layer-metadata'
    ),
    url(
        r'^analysis/layer-archive/(?P<layer_id>\d+)',
        layer_archive,
        name='layer-archive'
    ),
    url(
        r'^analysis/layer-list/'
        r'(?P<layer_purpose>(hazard|exposure|aggregation|impact))'
        r'(?:/(?P<layer_category>\w*))?'
        r'(?:/(?P<bbox>[,.\d-]*))?',
        layer_list,
        name='layer-list'
    ),
    url(
        r'^analysis/layer-panel'
        r'(?:/(?P<bbox>[\[\],.\d-]*))?',
        layer_panel,
        name='layer-panel'
    ),
    url(
        r'^analysis/extent/validation/',
        validate_analysis_extent,
        name='validate-analysis-extent'
    ),
    url(
        r'^analysis/extent/calculate/',
        validate_analysis_extent,
        name='calculate-area'
    ),
    url(
        r'^analysis/rerun/'
        r'(?P<analysis_id>\d+)',
        rerun_analysis,
        name='rerun-analysis'
    ),
    url(
        r'^analysis/cancel/'
        r'(?P<analysis_id>\d+)',
        cancel_analysis,
        name='cancel-analysis'
    ),
    url(
        r'^analysis/check/'
        r'(?P<analysis_id>\d+)',
        analysis_json,
        name='check-analysis'
    ),
    url(
        r'^analysis/toggle-saved/'
        r'(?P<analysis_id>[-\d]+)',
        toggle_analysis_saved,
        name='toggle-analysis-saved'
    ),
    url(
        r'^analysis/report/'
        r'(?P<analysis_id>\d+)/'
        r'(?P<data_type>(map|table|reports|all))',
        download_report,
        name='download-report'
    ),
    url(
        r'^analysis/summary/'
        r'(?P<impact_id>[-\d]+)/',
        analysis_summary,
        name='analysis-summary'
    ),

    # Metasearch
    url(
        r'^metasearch/$',
        metasearch.index,
        name='metasearch'
    ),
    url(
        r'^metasearch/csw_ajax$',
        metasearch.csw_ajax,
        name='metasearch_csw_ajax'
    ),
    url(
        r'^metasearch/add_layer$',
        metasearch.add_layer,
        name='metasearch_add_layer'
    ),
    url(
        r'^metasearch/add_layer_dialog',
        metasearch.show_add_layer_dialog,
        name='metasearch_add_layer_dialog'
    ),
    url(
        r'^metasearch/show_metadata',
        metasearch.show_metadata,
        name='metasearch_show_metadata'
    ),

    url(
        r'^metasearch/wfs_proxy',
        metasearch.wfs_proxy,
        name='metasearch_wfs_proxy'
    ),
)

forms.py
# coding=utf-8
import logging

from django import forms
from django.forms import models

from geonode.layers.models import Layer
from geonode.people.models import Profile
from geosafe.models import Analysis

__author__ = 'ismailsunni'

LOG = logging.getLogger(__name__)


class AnalysisCreationForm(models.ModelForm):
    """A form for creating an event."""

    class Meta:
        model = Analysis
        fields = (
            'user_title',
            'user_extent',
            'exposure_layer',
            'hazard_layer',
            'aggregation_layer',
            'impact_function_id',
            'extent_option',
            'keep',
        )

    user_title = forms.CharField(
        label='Analysis Title',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Default title generated'})
    )

    user_extent = forms.CharField(
        label='Analysis Extent',
        required=False,
    )

    exposure_layer = forms.ModelChoiceField(
        label='Exposure Layer',
        required=True,
        queryset=Layer.objects.filter(
            inasafe_metadata__layer_purpose='exposure'),
        widget=forms.Select(
            attrs={'class': 'form-control'})
    )

    hazard_layer = forms.ModelChoiceField(
        label='Hazard Layer',
        required=True,
        queryset=Layer.objects.filter(
            inasafe_metadata__layer_purpose='hazard'),
        widget=forms.Select(
            attrs={'class': 'form-control'})
    )

    aggregation_layer = forms.ModelChoiceField(
        label='Aggregation Layer',
        required=False,
        queryset=Layer.objects.filter(
            inasafe_metadata__layer_purpose='aggregation'),
        widget=forms.Select(
            attrs={'class': 'form-control'})
    )

    impact_function_id = forms.ChoiceField(
        label='Impact Function ID',
        required=True,
    )

    keep = forms.BooleanField(
        label='Save Analysis',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        exposure_layer = kwargs.pop('exposure_layer', None)
        hazard_layer = kwargs.pop('hazard_layer', None)
        impact_function_ids = kwargs.pop('impact_functions', None)
        super(AnalysisCreationForm, self).__init__(*args, **kwargs)
        if exposure_layer:
            self.fields['exposure_layer'].queryset = exposure_layer
        if hazard_layer:
            self.fields['hazard_layer'].queryset = hazard_layer
        if impact_function_ids:
            self.fields['impact_function_id'].choices = [
                (impact_function['id'], impact_function['name'])
                for impact_function in impact_function_ids]

    def save(self, commit=True):
        instance = super(AnalysisCreationForm, self).save(commit=False)
        if self.user.username:
            instance.user = self.user
        else:
            instance.user = Profile.objects.get(username='AnonymousUser')
        instance.save()
        return instance


class MetaSearchForm(forms.Form):

    class Meta:
        fields = (
            'csw_url',
            'keywords',
            'user',
            'password',
        )

    csw_url = forms.CharField(
        label='CSW URL',
        help_text='URL to CSW endpoint',
        required=True)
    keywords = forms.CharField(
        help_text='Keywords to include in the search',
        required=False)
    user = forms.CharField(
        help_text='User to connect to CSW Endpoint',
        required=False)
    password = forms.CharField(
        help_text='Password to connect to CSW Endpoint',
        required=False,
        widget=forms.PasswordInput(render_value=True))

templates/geosafe/analysis/dynamic_scripts/create/main.html
{% load bootstrap_tags %}
{% load staticfiles %}
{% load i18n avatar_tags %}
<script type="text/javascript">

    /* Global window variable */

    var map;
    var exposure_layer;
    var hazard_layer;
    var impact_layer;
    var layer_stack = []; //let utilise this variable for keeping track of 3 layers: boney-bun
    var hazard_exposure_marker_groups = L.layerGroup();
    var hazard_exposure_rect_groups = L.layerGroup();
    var aggregation_layer;
    var is_legend = false;
    var is_hazard = false;
    var is_exposure = false;
    var is_impact = false;

    var exposure_layer_cbo = $("#id_exposure_layer");
    var hazard_layer_cbo = $("#id_hazard_layer");
    var aggregation_layer_cbo = $("#id_aggregation_layer");
    var impact_function_cbo = $("#id_impact_function_id");
    var last_impact_id;
    var slider_exposure_val = 5, slider_hazard_val = 5, slider_impact_val = 5;
    var not_logged_warning = undefined;

    {# Common function for global use #}

    /**
     * Zoom to the current extent provided.
     *
     * @param map: leaflet map object
     * @param bbox: format: js array of [xmin,ymin,xmax,ymax]
     */
    function zoom_to_box(map, bbox) {
        var bounds = [
            [bbox[1], bbox[0]],
            [bbox[3], bbox[2]]
        ];
        map.fitBounds(bounds);
    }

    /**
     * Display a little warning if no layer is selected.
     */
    function check_layer_empty() {
        var exp_count = $(".exposure.section .option .list ul li").length;
        var haz_count = $(".hazard.section .option .list ul li").length;

        if (exp_count + haz_count == 0) {
            show_info_text(
                '<span class="text-danger">Extent Changed</span>',
                '<span class="alert-danger">No usable layer in current extent</span>',
                'alert-danger');
        }
        else if (exp_count == 0) {
            show_info_text(
                '<span class="text-danger">Extent Changed</span>',
                '<span class="alert-danger">No usable exposure layer in current extent</span>',
                'alert-danger');
        }
        else if (haz_count == 0) {
            show_info_text(
                '<span class="text-danger">Extent Changed</span>',
                '<span class="alert-danger">No usable hazard layer in current extent</span>',
                'alert-danger');
        }
    }

    /**
     * Display warning at the bottom
     *
     * @param title
     * @param content
     * @param context_class: bootstrap context class to apply
     */
    function show_info_text(title, content, context_class) {
        var $info_box = $(".info-box");
        //add message when a user not login
        if (not_logged_warning != undefined)
        {
            context_class = 'alert-danger';
            content += not_logged_warning;
        }

        if (context_class) {
            $info_box.addClass(context_class);
        }
        else {
            $info_box.attr('class', 'info-box text-center panel-body');
        }
        $info_box.find(".info-title").html(title);
        $info_box.find(".info-text").html(content);
    }

    /**
     * Dismiss warning text at the bottom
     *
     * @param title
     */
    function dissmiss_info_text(title) {
        if ($(".info-box .info-title").text() == title) {
            show_info_text("", "");
        }
    }

    /**
     * Specific warning that the analysis extent is too big.
     */
    function warn_analysis_zoom_limit() {
        var zoom_level = map.getZoom();
        var title = 'Analysis Extent Too Big'
        if (zoom_level < 10) {
            show_info_text(title, 'You might want to zoom in to perform analysis.');
        }
        else {
            dissmiss_info_text(title);
        }
    }

    /**
     * Send request to run analysis.
     *
     * The request detail itself is given from modal form.
     */
    function run_analysis() {
        var $keep = $("#confirm_save_analysis");
        if ($keep && $keep.prop('checked')) {
            $("#id_keep").prop('checked', true);
        }
        else {
            $("#id_keep").prop('checked', false);
        }

        {# Copy user title #}
        var $user_title = $("#confirm_user_title");
        $("#id_user_title").val($user_title.val());

        {# Copy user extent #}
        var $user_extent = $("#confirm_user_extent");
        $("#id_user_extent").val($user_extent.val());

        var $analysis_form = $(".analysis.section form");
        $.post($analysis_form.attr('action'), $analysis_form.serialize(), function (data) {
            if (data && data.success) {
                window.location.href = data.redirect;
            }
        });
    }

    /**
     * Show the analysis summary infographic.
     *
     * A general infographic about the analysis.
     */
    function show_analysis_summary() {
        if (last_impact_id == undefined) {
            show_info_text('Show Analysis Summary', 'Please select desired impact layer first, before viewing analysis summary.')
            return;
        }
        var selected_impact_id = last_impact_id;
        var url = '{% url "geosafe:analysis-summary" impact_id=-1 %}';
        url = url.replace("-1", selected_impact_id);
        $.get(url, function (data) {
            if (data) {
                $("#impact-card-modal").replaceWith(data);
                $("#impact-card-modal").modal();
                var impact_layer_title = $("#impact-option a[data-id='" + selected_impact_id + "']").text();
                show_info_text('Show Analysis Summary', 'Showing summary for ' + impact_layer_title);

                $(document).ready(function () {

                    $(".save-analysis input").change(function () {
                        var id = $(this).attr('data-id');
                        var urlpattern = '{% url "geosafe:toggle-analysis-saved" analysis_id=-1 %}';
                        toggle_analysis_saved(urlpattern, id);
                    });
                });
            }
        });
    }

    /**
     * Show url inside frame
     *
     * Useful to display PDF report
     *
     * @param title
     * @param url
     */
    function show_in_iframe(title, url) {
        var $iframe_modal = $("#iframe-modal");
        $iframe_modal.find("#iframe_label").text(title);
        $iframe_modal.find("iframe").attr('src', url);
        $iframe_modal.modal();
    }

    /**
     * Check popover tooltips status.
     *
     * Useful for displaying tooltip to explain what to do.
     */
    function check_popover() {
        var $exposure_popover = $("#exposure-section-link");
        var $hazard_popover = $("#hazard-section-link");
        var $run_analysis_popover = $("#run-analysis-submit-button");

        $('body').on('click', function () {
            $('[data-toggle="popover"]').popover('hide');
        });

        {# show hazard popover when document first loaded #}
        if (!$hazard_popover.hasClass('set')) {
            $hazard_popover.popover('show');
            return;
        }
        {# show exposure popover if hazard is selected #}
        if (!$exposure_popover.hasClass('set')) {
            $exposure_popover.popover('show');
            return;
        }

        {# show run button popover if hazard and exposure were selected #}
        {% if not analysis %}
                var analysis_url = '{% url 'geosafe:calculate-area' %}';
                /*var post_data = {
                    'hazard_id': {{ analysis.hazard_layer_id }},
                    'exposure_id': {{ analysis.exposure_layer_id }},
                    'view_extent': '{{ analysis.user_extent }}'
                };*/
                var post_data = {
                'hazard_id': hazard_layer_cbo.find('option:selected').val(),
                'exposure_id': exposure_layer_cbo.find('option:selected').val(),
                'view_extent': map.getBounds().toBBoxString()
            };
            var both_selected = 'Hazard and exposure are selected. ';
            var run_message = '';
            var allow_message = '';

                $.post(analysis_url, post_data, function (data) {
                    if (data) {
                        area = data['area'] / 1000000;
                        formatted_area = numeral(area).format('0,0');

                        if (data['is_valid']) {
                            allow_message = 'You can now run analysis.';
                        } else {
                            allow_message = 'You can\'t run analysis. Please reduce extent';
                        }
                        run_message = both_selected + 'The selected analysis extent is ' + formatted_area + ' m2. ' + allow_message;
                        $run_analysis_popover.popover({title: "Run Analysis", content: run_message});
                        $run_analysis_popover.popover('show');
                    } else {
                        $run_analysis_popover.popover({title: "Run Analysis", content: "If hazard and exposure were selected, you can run analysis"});
                        $run_analysis_popover.popover('show');
                    }
                });
        {% endif %}

    }

    /**
     * Generate both markers and rectangles in one go to save bandwidth
     *
     * @param layer_id
     * @param category
     */
    function show_marker(layer_id, category) {
        $.get('{% url 'geosafe:layer-tiles' %}', {'layer_id': layer_id}, function (data) {

            //default use of the marker
            var marker = L.marker([data['layer_bbox_y0'], data['layer_bbox_x0']], {
                title:data['layer_name']
            });
            marker.on('click', function (event) {
                zoom_to_box(map, [data['layer_bbox_x0'], data['layer_bbox_y0'], data['layer_bbox_x1'], data['layer_bbox_y1']]);

            });
            hazard_exposure_marker_groups.addLayer(marker);

            //use later, particularly if zoom > 10
            bounds = [[data['layer_bbox_y0'], data['layer_bbox_x0']], [data['layer_bbox_y1'], data['layer_bbox_x1']]];
            var rect_layer;

            if (category == "hazard") {
                rect_layer = L.rectangle(bounds, {
                    color: "#2c689c",
                    opacity: 0.3,
                    fill: false,
                    weight: 1
                });
            } else if (category == "exposure") {
                rect_layer = L.rectangle(bounds, {
                    color: "#ff7800",
                    opacity: 0.3,
                    fill: false,
                    weight: 1
                });
            }
            if(rect_layer != undefined) {
                rect_layer.bindTooltip(data['layer_name'], {sticky: true});
                hazard_exposure_rect_groups.addLayer(rect_layer);
            }
        });
    }

    /**
     * Check analysis extent
     */
    function check_analysis_extent(hazard_id, exposure_id) {

        return {
            'is_valid': is_valid,
            'reason': reason
        }
    }

</script>

{% include "geosafe/analysis/dynamic_scripts/create/side_panel.html" %}
{% include "geosafe/analysis/dynamic_scripts/create/transparency_control.html" %}

templates/geosafe/analysis/dynamic_scripts/create/transparency_control.html
{% load bootstrap_tags %}
{% load staticfiles %}
{% load i18n avatar_tags %}

{# UX for transparency control #}
<script type="text/javascript">

    /**
     * Function to set layer transparency according to slider
     */
    function set_transparency() {
        var exposure_id = $(".exposure.section a.selected").attr('data-id');
        var hazard_id = $(".hazard.section a.selected").attr('data-id');
        var impact_id = $(".impact-option a.selected").attr('data-id');

        //Using slider from https://github.com/seiyria/bootstrap-slider
        //there are two slider: jquery and seiyria's version
        //calling slider with bootstrapSlider to distinguish between them according to: http://stackoverflow.com/questions/26691018/using-bootstrap-slider-with-jquery-ui
        var new_exposure_opacity = $('#exposure-slider').bootstrapSlider('getValue');
        if (exposure_id != undefined && new_exposure_opacity != slider_exposure_val) {
            slider_exposure_val = new_exposure_opacity;
            update_map(exposure_id, 'exposure');
            $('#exposure-slider').bootstrapSlider('setValue', slider_exposure_val);
        }

        var new_hazard_opacity = $('#hazard-slider').bootstrapSlider('getValue');
        if (hazard_id != undefined && new_hazard_opacity != slider_hazard_val) {
            slider_hazard_val = new_hazard_opacity;
            update_map(hazard_id, 'hazard');
            $('#hazard-slider').bootstrapSlider('setValue', slider_hazard_val);
        }

        var new_impact_opacity = $('#impact-slider').bootstrapSlider('getValue');
        if (impact_id != undefined && new_impact_opacity != slider_impact_val) {
            slider_impact_val = new_impact_opacity;
            update_map(impact_id, 'impact');
            $('#hazard-slider').bootstrapSlider('setValue', slider_impact_val);
        }
    }

    /**
     * Add layer only if it doesn't exist in stack_layer.
     *
     * update it, otherwise.
     *
     * @param map: leaflet map object
     * @param layer_tiles_url: the layer tiles url
     * @param layer: layer object
     * @param layer_purpose: layer purpose (hazard, exposure, impact)
     */
    function add_layer(map, layer_tiles_url, layer, layer_purpose) {
        var slider_val = 0;
        if (layer_purpose == 'exposure') {
            slider_val = slider_exposure_val;
        } else if (layer_purpose == 'hazard') {
            slider_val = slider_hazard_val;
        } else if (layer_purpose == 'impact') {
            slider_val = slider_impact_val;
        }
        else {
            slider_val = 0.8;
        }

        layer = L.tileLayer(layer_tiles_url,
            {
                'opacity': slider_val / 10
            });
        if (layer != null) {
            // add layer if doesn't exist
            if ($.inArray(layer_tiles_url, layer_stack) == -1) {
                layer_stack.push(layer_tiles_url);
                map.addLayer(layer);
            } else {
                // update layer by removed the old one, replace with the new properties
                for (var key in map._layers) {
                    var temp_layer = map._layers[key];
                    if (temp_layer._url === layer_tiles_url) {
                        map.removeLayer(temp_layer);
                        map.addLayer(layer);
                        break;
                    }
                }
            }
            return layer;
        }
    }

    /**
     * Remove layer only if it exist in layer_stack.
     *
     * @param layer_id: layer object
     */
    function remove_layer(targeted_tiles_url) {
        layer_stack.splice($.inArray(targeted_tiles_url, layer_stack),1);
    }

    /**
     * Update map if user change transparency
     *
     * @param layer_id: the layer id
     * @param layer_purpose: layer purpose (hazard, exposure, impact)
     */
    function update_map(layer_id, layer_purpose) {
        $.get('{% url 'geosafe:layer-tiles' %}', {'layer_id': layer_id}, function (data) {
            var layer_tiles_url = data['layer_tiles_url'];
            var layer_bbox_x0 = data['layer_bbox_x0'];
            var layer_bbox_x1 = data['layer_bbox_x1'];
            var layer_bbox_y0 = data['layer_bbox_y0'];
            var layer_bbox_y1 = data['layer_bbox_y1'];
            var layer_name = data['layer_name'];
            var legend_url = data['legend_url'];
            var current_bounds = map.getBounds();
            var corner1 = L.latLng(layer_bbox_y1, layer_bbox_x1);
            var corner2 = L.latLng(layer_bbox_y0, layer_bbox_x0);
            var layer_bounds = L.latLngBounds(corner1, corner2);


            //show legend
            if (is_legend == false) {
                is_legend = true;
                $(".legend").toggle(is_legend);
            }

            if (layer_purpose == 'exposure') {
                if (is_exposure == false) {
                    is_exposure = true;
                    $("#legend-exposure-body").toggle(is_exposure);
                }

                exposure_layer = add_layer(map, layer_tiles_url, exposure_layer, 'exposure');
                $("#legend-exposure-name").text(layer_name);
                $("#exposure-legend-img").attr("src", legend_url);
                exposure_layer.setZIndex(1);
            } else if (layer_purpose == 'hazard') {
                if (is_hazard == false) {
                    is_hazard = true;
                    $("#legend-hazard-body").toggle(is_hazard);
                }
                hazard_layer = add_layer(map, layer_tiles_url, hazard_layer, 'hazard');
                $("#legend-hazard-name").text(layer_name);
                $("#hazard-legend-img").attr("src", legend_url);
                hazard_layer.setZIndex(2);

            } else if (layer_purpose == 'aggregation') {
                aggregation_layer = add_layer(map, layer_tiles_url, aggregation_layer, null);
                aggregation_layer.setZIndex(3);
            }
            else if (layer_purpose == 'impact') {
                if (is_impact == false) {
                    is_impact = true;
                    $("#legend-impact-body").toggle(is_impact);
                }
                impact_layer = add_layer(map, layer_tiles_url, impact_layer, 'impact');
                $("#legend-impact-name").text(layer_name);
                $("#impact-legend-img").attr("src", legend_url);
                impact_layer.setZIndex(4);
            }

            // Zooming magic
            // If only one of the 3 layers is selected then zoom to the layer
            {% if not analysis %}
                if ((is_hazard != is_exposure) != is_impact) {
                    map.fitBounds([[layer_bbox_y1, layer_bbox_x1], [layer_bbox_y0, layer_bbox_x0]]);
                }
                // If hazard and exposure selected intersect both extents
                if ((layer_purpose == 'hazard' && is_exposure) || (layer_purpose == 'exposure' && is_hazard)) {
                    // Intersect current extent to the input layer's extent
                    var new_sw = [
                        Math.max(
                            current_bounds.getSouthWest().lat,
                            layer_bounds.getSouthWest().lat),
                        Math.max(
                            current_bounds.getSouthWest().lng,
                            layer_bounds.getSouthWest().lng)];
                    var new_ne = [
                        Math.min(
                            current_bounds.getNorthEast().lat,
                            layer_bounds.getNorthEast().lat),
                        Math.min(
                            current_bounds.getNorthEast().lng,
                            layer_bounds.getNorthEast().lng)];
                    map.fitBounds([new_sw, new_ne]);
                }
            {% else %}
                // Use case: the user toggle impact layer off and on
                if (layer_purpose == 'impact') {
                    user_extent_string = map.getBounds().toBBoxString().split(',');
                } else {
                    user_extent_string = [{{ analysis.user_extent }}];
                }
                zoom_to_box(map, user_extent_string);
            {% endif %}
        });
    }

    $(document).ready(function () {
        $(".transparency-slider").bootstrapSlider().on('slide', set_transparency);
        $(".legend").mouseover(function(){
           map.dragging.disable();
        });
        $(".legend").mouseout(function(){
           map.dragging.enable();
        });
    });
</script>