urls.py
__author__ = 'ismailsunni'

from django.conf.urls import patterns, url

from geosafe.views import metasearch
from geosafe.views.analysis import (
    AnalysisListView,
    AnalysisCreateView,
    AnalysisDetailView,
    impact_function_filter,
    layer_tiles,
    layer_metadata,
    layer_archive,
    layer_list, rerun_analysis,
    analysis_json, toggle_analysis_saved, download_report, layer_panel,
    analysis_summary, cancel_analysis, validate_analysis_extent)

urlpatterns = patterns(
    '',
    url(
        r'^analysis/create(?:/(?P<pk>\d*))?$',
        AnalysisCreateView.as_view(),
        name='analysis-create'
    ),
    url(
        r'^analysis/(?:/user/(?P<user>\d*))?$',
        AnalysisListView.as_view(),
        name='analysis-list'
    ),
    url(
        r'^analysis/impact-function-filter$',
        impact_function_filter,
        name='impact-function-filter'
    ),
    url(
        r'^analysis/(?P<pk>\d+)$',
        AnalysisDetailView.as_view(),
        name='analysis-detail'
    ),
    url(
        r'^analysis/layer-tiles$',
        layer_tiles,
        name='layer-tiles'
    ),
    url(
        r'^analysis/layer-metadata/(?P<layer_id>\d+)',
        layer_metadata,
        name='layer-metadata'
    ),
    url(
        r'^analysis/layer-archive/(?P<layer_id>\d+)',
        layer_archive,
        name='layer-archive'
    ),
    url(
        r'^analysis/layer-list/'
        r'(?P<layer_purpose>(hazard|exposure|aggregation|impact))'
        r'(?:/(?P<layer_category>\w*))?'
        r'(?:/(?P<bbox>[,.\d-]*))?',
        layer_list,
        name='layer-list'
    ),
    url(
        r'^analysis/layer-panel'
        r'(?:/(?P<bbox>[\[\],.\d-]*))?',
        layer_panel,
        name='layer-panel'
    ),
    url(
        r'^analysis/extent/validation/',
        validate_analysis_extent,
        name='validate-analysis-extent'
    ),
    url(
        r'^analysis/extent/calculate/',
        validate_analysis_extent,
        name='calculate-area'
    ),
    url(
        r'^analysis/rerun/'
        r'(?P<analysis_id>\d+)',
        rerun_analysis,
        name='rerun-analysis'
    ),
    url(
        r'^analysis/cancel/'
        r'(?P<analysis_id>\d+)',
        cancel_analysis,
        name='cancel-analysis'
    ),
    url(
        r'^analysis/check/'
        r'(?P<analysis_id>\d+)',
        analysis_json,
        name='check-analysis'
    ),
    url(
        r'^analysis/toggle-saved/'
        r'(?P<analysis_id>[-\d]+)',
        toggle_analysis_saved,
        name='toggle-analysis-saved'
    ),
    url(
        r'^analysis/report/'
        r'(?P<analysis_id>\d+)/'
        r'(?P<data_type>(map|table|reports|all))',
        download_report,
        name='download-report'
    ),
    url(
        r'^analysis/summary/'
        r'(?P<impact_id>[-\d]+)/',
        analysis_summary,
        name='analysis-summary'
    ),

    # Metasearch
    url(
        r'^metasearch/$',
        metasearch.index,
        name='metasearch'
    ),
    url(
        r'^metasearch/csw_ajax$',
        metasearch.csw_ajax,
        name='metasearch_csw_ajax'
    ),
    url(
        r'^metasearch/add_layer$',
        metasearch.add_layer,
        name='metasearch_add_layer'
    ),
    url(
        r'^metasearch/add_layer_dialog',
        metasearch.show_add_layer_dialog,
        name='metasearch_add_layer_dialog'
    ),
    url(
        r'^metasearch/show_metadata',
        metasearch.show_metadata,
        name='metasearch_show_metadata'
    ),

    url(
        r'^metasearch/wfs_proxy',
        metasearch.wfs_proxy,
        name='metasearch_wfs_proxy'
    ),
)

models.py
from __future__ import absolute_import

import urlparse

from celery.result import AsyncResult
from django.core.files.base import File
from django.core.urlresolvers import reverse
from django.db import models
from datetime import datetime

from geonode.layers.models import Layer
from geosafe.app_settings import settings

# geosafe
# list of tags to get to the InaSAFE keywords.
# this is stored in a list so it can be easily used in a for loop

ISO_METADATA_KEYWORD_NESTING = [
    '{http://www.isotc211.org/2005/gmd}identificationInfo',
    '{http://www.isotc211.org/2005/gmd}MD_DataIdentification',
    '{http://www.isotc211.org/2005/gmd}supplementalInformation',
    'inasafe_keywords']

# flat xpath for the keyword container tag
ISO_METADATA_KEYWORD_TAG = '/'.join(ISO_METADATA_KEYWORD_NESTING)


class GeoSAFEException(BaseException):
    pass


# Create your models here.
class Metadata(models.Model):
    """Represent metadata for a layer."""
    layer = models.OneToOneField(
        Layer, primary_key=True, related_name='inasafe_metadata')
    layer_purpose = models.CharField(
        verbose_name='Purpose of the Layer',
        max_length=20,
        blank=True,
        null=True,
        default=''
    )
    category = models.CharField(
        verbose_name='The category of layer purpose that describes a kind of'
                     'hazard or exposure this layer is',
        max_length=30,
        blank=True,
        null=True,
        default=''
    )
    keywords_xml = models.TextField(
        verbose_name='Full representation of InaSAFE keywords in xml format',
        blank=True,
        null=True,
        default=''
    )


class Analysis(models.Model):
    """Represent GeoSAFE analysis"""
    HAZARD_EXPOSURE_CURRENT_VIEW_CODE = 1
    HAZARD_EXPOSURE_CODE = 2
    HAZARD_EXPOSURE_BBOX_CODE = 3

    HAZARD_EXPOSURE_CURRENT_VIEW_TEXT = (
        'Use intersection of hazard, exposure, and current view extent')
    HAZARD_EXPOSURE_TEXT = 'Use intersection of hazard and exposure'
    HAZARD_EXPOSURE_BBOX_TEXT = (
        'Use intersection of hazard, exposure, and bounding box')

    EXTENT_CHOICES = (
        (HAZARD_EXPOSURE_CURRENT_VIEW_CODE, HAZARD_EXPOSURE_CURRENT_VIEW_TEXT),
        (HAZARD_EXPOSURE_CODE, HAZARD_EXPOSURE_TEXT),
        # Disable for now
        # (HAZARD_EXPOSURE_BBOX_CODE, HAZARD_EXPOSURE_BBOX_TEXT),
    )

    class Meta:
        verbose_name_plural = 'Analyses'

    user_title = models.CharField(
        max_length=255,
        verbose_name='User defined title for analysis',
        help_text='Title to assign after analysis is generated.',
        blank=True,
        null=True,
    )
    user_extent = models.CharField(
        max_length=255,
        verbose_name='Analysis extent',
        help_text='User defined BBOX for analysis extent',
        blank=True,
        null=True,
    )
    exposure_layer = models.ForeignKey(
        Layer,
        verbose_name='Exposure Layer',
        help_text='Exposure layer for analysis.',
        blank=False,
        null=False,
        related_name='exposure_layer'
    )
    hazard_layer = models.ForeignKey(
        Layer,
        verbose_name='Hazard Layer',
        help_text='Hazard layer for analysis.',
        blank=False,
        null=False,
        related_name='hazard_layer'
    )
    aggregation_layer = models.ForeignKey(
        Layer,
        verbose_name='Aggregation Layer',
        help_text='Aggregation layer for analysis.',
        blank=True,
        null=True,
        related_name='aggregation_layer'
    )
    impact_function_id = models.CharField(
        max_length=100,
        verbose_name='ID of Impact Function',
        help_text='The ID of Impact Function used in the analysis.',
        blank=False,
        null=False
    )
    extent_option = models.IntegerField(
        choices=EXTENT_CHOICES,
        default=HAZARD_EXPOSURE_CODE,
        verbose_name='Analysis extent',
        help_text='Extent option for analysis.'
    )

    impact_layer = models.ForeignKey(
        Layer,
        verbose_name='Impact Layer',
        help_text='Impact layer from this analysis.',
        blank=True,
        null=True,
        related_name='impact_layer'
    )

    task_id = models.CharField(
        max_length=40,
        verbose_name='Task UUID',
        help_text='Task UUID that runs analysis',
        blank=True,
        null=True
    )

    task_state = models.CharField(
        max_length=10,
        verbose_name='Task State',
        help_text='Task State recorded in the model',
        blank=True,
        null=True
    )

    keep = models.BooleanField(
        verbose_name='Keep impact result',
        help_text='True if the impact will be kept',
        blank=True,
        default=False,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Author',
        help_text='The author of the analysis',
        blank=True,
        null=True
    )

    report_map = models.FileField(
        verbose_name='Report Map',
        help_text='The map report of the analysis',
        blank=True,
        null=True,
        upload_to='analysis/report/'
    )

    report_table = models.FileField(
        verbose_name='Report Table',
        help_text='The table report of the analysis',
        blank=True,
        null=True,
        upload_to='analysis/report/'
    )

    start_time = models.DateTimeField(
        'start_time',
        default=datetime.now
    )

    end_time = models.DateTimeField(
        'end_time',
        default=datetime.now
    )

    def assign_report_map(self, filename):
        try:
            self.report_map.delete()
        except BaseException:
            pass
        self.report_map = File(open(filename))

    def assign_report_table(self, filename):
        try:
            self.report_table.delete()
        except BaseException:
            pass
        self.report_table = File(open(filename))

    def get_task_result(self):
        """
        :return: celery AsyncResult
        :rtype: celery.result.AsyncResult
        """
        return AsyncResult(self.task_id)

    def get_label_class(self):
        state = self.get_task_state()
        if state == 'SUCCESS':
            return 'success'
        elif state == 'FAILURE':
            return 'danger'
        else:
            return 'info'

    def get_task_state(self):
        """Check task state

        State need to be evaluated from task result.
        However after a certain time, the task result is removed from broker.
        In this case, the state will always return 'PENDING'. For this, we
        receive the actual result from self.state, which is the cached state

        :return: task state string
        :rtype: str
        """
        result = self.get_task_result()
        if not result.task_id:
            # If no task_id, we don't have any task yet.
            return 'FAILURE'
        return self.task_state if result.state == 'PENDING' else result.state

    def get_default_impact_title(self):
        layer_name = '%s on %s' % (
            self.hazard_layer.name,
            self.exposure_layer.name
        )
        return layer_name

    _impact_function_list = []

    @classmethod
    def impact_function_list(cls):
        if not cls._impact_function_list:
            from geosafe.tasks.headless.analysis import filter_impact_function
            cls._impact_function_list = filter_impact_function.delay().get()
        return cls._impact_function_list

    def impact_function_name(self):
        for i in self.impact_function_list():
            if i['id'] == self.impact_function_id:
                return i['name']
        return ''

    @classmethod
    def get_layer_url(cls, layer):
        layer_id = layer.id
        layer_url = reverse(
            'geosafe:layer-archive',
            kwargs={'layer_id': layer_id})
        layer_url = urlparse.urljoin(settings.GEONODE_BASE_URL, layer_url)
        return layer_url

    @classmethod
    def get_base_layer_path(cls, layer):
        base_file, _ = layer.get_base_file()
        return base_file.file.path

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, run_analysis_flag=True):
        super(Analysis, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields)


# needed to load signals

templates/geosafe/analysis/detail.html
{% extends 'geonode_base.html' %}
{% load bootstrap_tags %}
{% load leaflet_tags %}
{% block extra_head %}
    {% leaflet_css %}
{% endblock extra_head %}
{% block body_outer %}
    <div class="page-header">
        <h2 class="page-title">Analysis Details</h2>
    </div>
    <div class="row">
        <div class="container-fluid pad0x">
            <div class="col-md-8" id="inner-body">
                <div id="map" style="width: 100%; height: 600px; position:relative;">
                </div>
            </div>
            <div class="col-md-4">
                <div>
                    <p>Exposure Layer: <a
                            href="{% url 'layer_detail' layername=analysis.exposure_layer.typename %}">{{ analysis.exposure_layer }}</a>
                    </p>

                    <p>Hazard Layer: <a
                            href="{% url 'layer_detail' layername=analysis.hazard_layer.typename %}">{{ analysis.hazard_layer }}</a>
                    </p>

                    <p>Aggregation Layer: <a
                            href="{% url 'layer_detail' layername=analysis.aggregation_layer.typename %}">{{ analysis.aggregation_layer }}</a>
                    </p>

                    <p>Impact Function ID: {{ analysis.impact_function_id }}</p>

                    <p>Extent: {{ analysis.get_extent_option_display }}</p>

                    <p>Impact Layer:
                        {% if not analysis.get_task_result %}
                                Analysis not yet running
                        {% elif analysis.get_task_result.successful %}
                            <a href="{% url 'layer_detail' layername=analysis.impact_layer.typename %}">{{ analysis.impact_layer }}</a>
                        {% else %}
                            Task Status:
                            <span class="label label-{{ analysis.get_label_class }}">
                            {{ analysis.get_task_result.state }}
                            </span>
                        {% endif %}
                        {% if analysis.get_task_result and analysis.get_task_result.state == "FAILURE" %}
                            <div class="panel panel-default">
                              <div class="panel-heading">
                                <h3 class="panel-title">Error Detail</h3>
                              </div>
                              <div class="panel-body">
                                  <p>{{ analysis.get_task_result.result }}</p>
                                  <p>{{ analysis.get_task_result.traceback }}</p>
                              </div>
                            </div>
                        {% endif %}
                    </p>
                    {% if analysis.get_task_result %}
                        {% if analysis.get_task_result.successful or analysis.get_task_result.failed %}
                            <p>
                                <form action="{% url 'geosafe:rerun-analysis' analysis_id=analysis.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" id="analysis_id" value="{{ analysis.id }}" />
                                    <button type="submit" class="btn btn-primary">Rerun Analysis</button>
                                </form>
                            </p>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock body_outer %}

{% block extra_script %}
    {% leaflet_js %}
    <script>
        (function () {
            // your page initialization code here
            // the DOM will be available here
            console.log("ready!");

            var map = L.map('map');

            function zoom_to_box(map, bbox) {
                var bounds = [
                    [bbox[1], bbox[0]],
                    [bbox[3], bbox[2]]
                ];
                map.fitBounds(bounds);
            }

            function add_layer(map, layer) {
                console.log(layer);
                tile_layer = L.tileLayer(layer['get_titles_url'],
                        {
                            'opacity': 0.8
                        });
                if (tile_layer != null) {
                    map.addLayer(tile_layer);
                }
            }

            var osm = L.tileLayer('http://otile{s}.mqcdn.com/tiles/1.0.0/{type}/{z}/{x}/{y}.{ext}', {
                type: 'map',
                ext: 'jpg',
                attribution: 'Tiles Courtesy of <a href="http://www.mapquest.com/">MapQuest</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
                subdomains: '1234'
            });

            var OpenMapSurfer_Roads = L.tileLayer('http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}', {
                noWrap: true,
                attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            });
            map.addLayer(OpenMapSurfer_Roads);
            var exposure_layer = [];
            var hazard_layer = [];
            var aggregation_layer = [];
            var impact_layer = [];

            exposure_layer['get_titles_url'] = "{{ analysis.exposure_layer.get_tiles_url|safe }}";
            hazard_layer['get_titles_url'] = "{{ analysis.hazard_layer.get_tiles_url|safe }}";
            aggregation_layer['get_titles_url'] = "{{ analysis.aggregation_layer.get_tiles_url|safe }}";
            impact_layer['get_titles_url'] = "{{ analysis.impact_layer.get_tiles_url|safe }}";


            add_layer(map, exposure_layer);
            add_layer(map, hazard_layer);
            add_layer(map, aggregation_layer);
            add_layer(map, impact_layer);
            {% if analysis.aggregation_layer.bbox_string %}
                zoom_to_box(map, [{{ analysis.aggregation_layer.bbox_string }}]);
            {% else %}
                zoom_to_box(map, [{{ analysis.exposure_layer.bbox_string }}]);
            {% endif %}

            {% if analysis.get_task_result %}
                {% if not analysis.get_task_result.successful and not analysis.get_task_result.failed %}
                    {# Automatic reload in 30 sec #}
                    setTimeout(function(){
                        window.location.reload()
                    }, 30000);
                {% endif %}
            {% endif %}
        })();

    </script>
{% endblock extra_script %}

templates/geosafe/analysis/legend.html
<div class="legend">
    <div id="legend-title">
        <a href="#" style="font-style: oblique; text-align: center;"><p>Legend</p></a>
    </div>
    <div id="legend-body">
        <div id="legend-hazard-body">
            <p>Hazard: <span id="legend-hazard-name"></span></p>
            <p><input class="transparency-slider" type="text" value="5" id="hazard-slider" data-slider-min="1"
                      data-slider-max="10"
                      data-slider-step="1" onchange="set_transparency();"></p>
            <p><img id="hazard-legend-img"/></p>
        </div>
        <div id="legend-exposure-body">
            <p>Exposure: <span id="legend-exposure-name"></span></p>
            <p><input class="transparency-slider" type="text" value="5" id="exposure-slider" data-slider-min="1"
                      data-slider-max="10"
                      data-slider-step="1" onchange="set_transparency();"></p>
            <p><img id="exposure-legend-img"/></p>
        </div>
        <div id="legend-impact-body">
            <p>Impact: <span id="legend-impact-name"></span></p>
            <p><input class="transparency-slider" type="text" value="5" id="impact-slider" data-slider-min="1"
                      data-slider-max="10"
                      data-slider-step="1" onchange="set_transparency();"></p>
            <p><img id="impact-legend-img"/></p>
        </div>
    </div>
</div>

templates/geosafe/analysis/list.html
{% extends 'geonode_base.html' %}
{% load staticfiles %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'geosafe/css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'geosafe/css/jquery.dynatable.css' %}" />
{% endblock %}
{% block body %}
    <style>
        .btn .fa-check{
            display: none;
        }
        .btn.active .fa-check{
            display: inline-block;
            color: #50cf5c;
        }
        .btn .fa-close{
            display: inline-block;
            color: #f15a2b;
        }
        .btn.active .fa-close{
            display: none;
        }
        .btn.processing .fa-close{
            display: none;
        }
        .btn .fa-spinner{
            display: none;
        }
        .btn.processing .fa-spinner{
            display: inline-block;
        }

        .save-analysis.processing .onoffswitch-inner,
        .save-analysis.processing .onoffswitch-switch{
            display: none;
        }
        .save-analysis.processing{
            width: auto;
        }
        .save-analysis.processing .processing-indicator{
            display: inline-block;
            white-space: nowrap;
            height: 30px;
            padding-left: 10px;
            padding-right: 10px;
            padding-top: 5px;
        }
        .save-analysis .processing-indicator{
            display: none;
        }

        #user-filter-group{
            margin-right: 10px;
        }

        .download-link{
            white-space: nowrap;
        }
    </style>
    <h1>List of Analysis</h1>
    <div>
        {% if analysis_list %}
            <div id="user-filter-group" class="btn-group" data-toggle="buttons">
                <label class="btn btn-primary active">
                    <input type="radio" name="user-filter" checked value="all">
                    All
                </label>
                <label class="btn btn-primary">
                    <input type="radio" name="user-filter" value="user">
                    {% if not user.username %}
                        Anonymous
                    {% else %}
                        Current users
                    {% endif %}
                </label>
            </div>
            <table id="analysis-list" class="table table-striped">
                <thead>
                <tr>
                    <th>User</th>
                    <th>Date Created</th>
{#                    <th>Exposure</th>#}
{#                    <th>Hazard</th>#}
{#                    <th>Aggregation</th>#}
{#                    <th>Extent</th>#}
                    <th>Impact Function Name</th>
                    <th>Result</th>
                    <th>View</th>
                    {% if user.username %}
                        <th>Save</th>
                    {% endif %}
                    <th>Download</th>
                </tr>
                </thead>
                <tbody>
                {% for analysis in analysis_list %}
                    <tr>
                        <td>
                            <a href="{{ analysis.user.get_absolute_url }}">{{ analysis.user.username }}</a>
                        </td>
                        <td>
                            {% if analysis.impact_layer %}
                                {{ analysis.impact_layer.date }}
                            {% else %}
                                Result not yet created
                            {% endif %}
                        </td>
{#                        <td>#}
{#                            <a href="{% url 'layer_detail' layername=analysis.exposure_layer.typename %}">{{ analysis.exposure_layer }}</a>#}
{#                        </td>#}
{#                        <td>#}
{#                            <a href="{% url 'layer_detail' layername=analysis.hazard_layer.typename %}">{{ analysis.hazard_layer }}</a>#}
{#                        </td>#}
{#                        <td>#}
{#                            <a href="{% url 'layer_detail' layername=analysis.aggregation_layer.typename %}">{{ analysis.aggregation_layer }}</a>#}
{#                        </td>#}
{#                        <td>#}
{#                            {{ analysis.get_extent_option_display }}#}
{#                        </td>#}
                        <td>
                            {{ analysis.impact_function_name }}
                        </td>
                        <td>
                            {% if not analysis.get_task_result %}
                                Analysis not yet running
                            {% elif analysis.get_task_state == 'SUCCESS' %}
                                <a href="{% url 'layer_detail' layername=analysis.impact_layer.typename %}"> {{ analysis.impact_layer }} <br /> Duration: {{ analysis.start_time|timesince:analysis.end_time }} </a>
                            {% else %}
                                <div>Task Status: <span class="label label-{{ analysis.get_label_class }}">{{ analysis.get_task_state }}</span></div>
                                        {{ analysis.hazard_layer }} on {{ analysis.exposure_layer }} <br />Start Time: {{ analysis.start_time }}
                                {% if analysis.get_task_state == 'FAILURE' %}
                                <div>
                                    <form action="{% url 'geosafe:rerun-analysis' analysis_id=analysis.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" id="analysis_id" value="{{ analysis.id }}" />
                                        <button type="submit" class="btn btn-primary">Rerun Analysis</button>
                                    </form>
                                </div>
                                {% elif analysis.get_task_state == 'PENDING' and user.is_superuser %}
                                <div>
                                    <form action="{% url 'geosafe:cancel-analysis' analysis_id=analysis.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" id="analysis_id" value="{{ analysis.id }}" />
                                        <button type="submit" class="btn btn-primary">Cancel Analysis</button>
                                    </form>
                                </div>
                                {% endif %}
                            {% endif %}
                        </td>
                        <td>
                            {% if analysis.report_map %}
                                <div>
                                    <a class="download-link" href="{% url 'geosafe:download-report' analysis_id=analysis.id data_type='map' %}">Map Report</a>
                                </div>
                            {% endif %}
                            {% if analysis.report_table %}
                                <div>
                                    <a class="download-link" href="{% url 'geosafe:download-report' analysis_id=analysis.id data_type='table' %}">Table Report</a>
                                </div>
                            {% endif %}
                            <div>
                                <a class="download-link" href="{% url 'geosafe:analysis-create' pk=analysis.id %}">Analysis Page</a>
                            </div>
                        </td>
                        {% if user.username %}
                        <td>
                            <div class="onoffswitch save-analysis">
                                <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox"
                                       id="save_analysis_{{ analysis.id }}"
                                       {% if analysis.keep %}checked{% endif %}
                                       data-id="{{ analysis.id }}">
                                <label class="onoffswitch-label" for="save_analysis_{{ analysis.id }}">
                                    <span class="processing-indicator">
                                        <i class="fa fa-spinner fa-spin"></i>
                                        PROCESSING
                                    </span>
                                    <span class="onoffswitch-inner"></span>
                                    <span class="onoffswitch-switch"></span>
                                </label>
                            </div>
                        </td>
                        {% endif %}
                        <td>
                            {% if analysis.impact_layer %}
                                <a href="{% url 'geosafe:download-report' analysis_id=analysis.id data_type='all' %}">Download</a>
                            {% else %}
                                Result not yet created
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No analysis yet. <a href="{% url "geosafe:analysis-create" %}">Why not creating one?</a></p>
        {% endif %}
    </div>
{% endblock %}

{% block extra_script %}
<script type="text/javascript" src="{% static 'geosafe/js/jquery.dynatable.js' %}">
</script>
<script type="text/javascript" src="{% static 'geosafe/js/analysis.js' %}"></script>
<script type="text/javascript">

$(document).ready(function(){

    var analysis_list_dynatable = $("#analysis-list")
            .bind('dynatable:init', function (e, dynatable) {
                dynatable.queries.functions['user'] = function(record, queryValue){
                    return $(record['user']).text() == queryValue;
                }
            }).dynatable().data('dynatable');

    $(".save-analysis input").change(function(){
        var id=$(this).attr('data-id');
        var urlpattern = '{% url "geosafe:toggle-analysis-saved" analysis_id=-1 %}';
        toggle_analysis_saved(urlpattern, id);
    });

    $("#user-filter-group label").on('click', function () {
        if($(this).find('input').val()=='all'){
            analysis_list_dynatable.queries.remove('user');
        }
        else{
            {% if user.username %}
                analysis_list_dynatable.queries.add('user', '{{ user.username }}');
            {% else %}
                analysis_list_dynatable.queries.add('user', 'AnonymousUser');
            {% endif %}
        }
        analysis_list_dynatable.process();
    });
});
</script>
{% endblock %}